lab02/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    # ex : /encuesta/
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar')
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here. 

def index(request):
    context = {
        'titulo' : "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo' : 'Respuesta',
        'nombre' : request.POST['nombre'],
        'clave'  : request.POST['password'],
        'educacion': request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render(request, 'encuesta/repuesta.html', context)

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method ="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Constraseña:
    <input type="password" name="passsword"><br>
    Educacion:
    <select name="educatcion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educacion obligatoria</option>
        <option value="formacion-profesional">Formacion Profesional</option>
        <option value="universidad">Universidad</option>
    </select><br>
    Nacionalidad:
    <input type="radio" name="nacionalidad"  value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad"  value="otra">Otra</input>
    Idiomas:
    <input type="checkbox" name="idiomas"  value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas"  value="inglés">Inglés</input>
    <input type="checkbox" name="idiomas"  value="fancés">Francés</input>
    <input type="checkbox" name="idiomas"  value="alemán">Alemán</input><br>
    Email:
    <input type="text" name="email"><br>
    //Botón de enviar
    <input type="submit" name="submit" value="Enviar"
</form>    

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }} </li>
    {% endfor %}
</ul>
<p>Email: {{ correo }} </p>
<p>Sitio Web: {{ website }} </p>