WEBPROJECT/ArduinoWeb/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('index.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

WEBPROJECT/index/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'index'

urlpatterns = [

    ##Inicio de la pagina
    path('', views.home, name='home')
    ,

    ##Control de la Iluminación de una casa
    path('homeduino', views.index_view, name = 'homeduino')
    ,
    
    ##Espacio de noticias
    path('infomatica',views.info, name = 'infomatica')
    ,

    ##Tienda de Componenetes
    path('TCE', views.TCE, name = 'TCE'),
    path('producto', views.producto, name='producto')
    ,
    path('categoria/<int:categoria_id>',views.indexByCategory,name='categoria'),
    ##API
    path('api/list',views.product_list),
    path('api/detail/<int:pk>',views.product_detail)
]

WEBPROJECT/index/models.py
from django.db import models

# Create your models here.

class Servicio(models.Model):
    

    nombre = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=300)
    push_date = models.DateField('date published')

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    push_date = models.DateField('date published')

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField(default=0,blank=True,null=True)
    imagen = models.ImageField(upload_to='productos',blank=True,null=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.nombre

WEBPROJECT/index/controller.py
import pyfirmata

##puerto = "\.\COM3" #Puerto COM de emulación en USB
pin = (2) #PIN donde va conectado el LED
pin = (3) #PIN donde va conectado el LED
pin = (4) #PIN donde va conectado el LED
pin = (5) #PIN donde va conectado el LED
##board = pyfirmata.Arduino(puerto)

def blueOn():
    board.digital[2].write(1)
    board.digital[3].write(0)
    board.digital[4].write(0)
    board.digital[5].write(0)
    print("Encendiendo AZUL")
def redOn():
    board.digital[2].write(0)
    board.digital[3].write(1)
    board.digital[4].write(0)
    board.digital[5].write(0)
    print("Encendiendo ROJO")
def greenOn():
    board.digital[2].write(0)
    board.digital[3].write(0)
    board.digital[4].write(1)
    board.digital[5].write(0)
    print("Encendiendo VERDE")
def yellowOn():
    board.digital[2].write(0)
    board.digital[3].write(0)
    board.digital[4].write(0)
    board.digital[5].write(1)
    print("Encendiendo AMARILLO")
def allOff():
    board.digital[2].write(0)
    board.digital[3].write(0)
    board.digital[4].write(0)
    board.digital[5].write(0)
    print("Apagando todas")

WEBPROJECT/index/views.py
from django.shortcuts import render, HttpResponse
from rest_framework.decorators import api_view
from .serializers import ProductSerializer
from index.controller import blueOn, greenOn, redOn , yellowOn, allOff
from django.shortcuts import render
from .models import Categoria, Producto
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def home (request):
    return render (request, 'home.html')

def info (request):
    return render (request, 'infomatica.html')

def index_view (request):
    if request.POST:
        id = request.POST['id']
        if int(id) == 1:
            redOn()
        elif int(id) == 2:
            greenOn()
        elif int(id) == 3:
            blueOn()
        elif int(id) == 4:
            yellowOn()
        elif int(id) == 5:
            allOff()
        print(id)
    return render(request, 'homeduino.html')

def TCE(request):
    product_list = Producto.objects.order_by('nombre')[:6]
    category_list = Categoria.objects.all()
    
    dicCategorias = {}
    for cat in category_list:
        dicCategorias[cat.id] = {
            'id' :cat.id,
            'nombre' : cat.nombre
        }
    request.session['nombrePagina'] = 'services categorias'
    request.session['category_list'] = dicCategorias
    
    context = { 
        'product_list': product_list,
    }
    return render(request, 'TCE.html', context)
    
def producto(request,producto_id):
    OBJproducto = Producto.objects.get(pk=producto_id)
    
    context = { 
        'producto': OBJproducto }
    return render(request, 'TCE.html', context)

def indexByCategory(request,categoria_id):
    objCategoria = Categoria.objects.get(pk=categoria_id)
    product_list = Producto.objects.filter( categoria = objCategoria)    
    category_list = Categoria.objects.all()
    context = { 
        'product_list': product_list
    }
    return render(request, 'TCE.html', context)


class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)

@csrf_exempt
def product_list(request):
    """
    List all code serie, or create a new serie.
    """
    if request.method == 'GET':
        producto = Producto.objects.all()
        serializer = ProductSerializer(producto, many=True)
        return JSONResponse(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ProductSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data, status=201)
        return JSONResponse(serializer.errors, status=400)

@csrf_exempt
def product_detail(request, pk):
    """
    Retrieve, update or delete a serie.
    """
    try:
        serie = Producto.objects.get(pk=pk)
    except Producto.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = ProductSerializer(serie)
        return JSONResponse(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = ProductSerializer(serie, data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        Producto.delete()
        return HttpResponse(status=204)

WEBPROJECT/index/templates/About.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>About</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
<link rel="stylesheet" href="About.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.1.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"logo": "images/default-logo.png"
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="About">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body"><header class="u-clearfix u-header u-header" id="sec-e304"><div class="u-clearfix u-sheet u-sheet-1">
        <a href="https://nicepage.com" class="u-image u-logo u-image-1">
          <img src="images/default-logo.png" class="u-logo-image u-logo-image-1">
        </a>
      </div></header> 
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-340a"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">Encuentranos como:&nbsp;<br>GREYMAC@gmail.com
        </p>
      </div></footer>
    <section class="u-backlink u-clearfix u-grey-80">
      <a class="u-link" href="https://nicepage.com/website-templates" target="_blank">
        <span>Website Templates</span>
      </a>
      <p class="u-text">
        <span>created with</span>
      </p>
      <a class="u-link" href="" target="_blank">
        <span>Website Builder Software</span>
      </a>. 
    </section>
  </body>
</html>

WEBPROJECT/index/templates/Casa.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="GREYMAC, GREYMAC, Página de servicios">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Casa</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
<link rel="stylesheet" href="Casa.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.1.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    
    
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Casa">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body">
    <section class="u-clearfix u-grey-5 u-section-1" id="carousel_5aca">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-text u-text-default u-text-palette-3-base u-text-1">GREYMAC</h2>
        <div class="u-clearfix u-expanded-width u-gutter-26 u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-size-20">
                <div class="u-layout-col">
                  <div class="u-align-center u-container-style u-layout-cell u-size-40 u-white u-layout-cell-1">
                    <div class="u-container-layout u-container-layout-1">
                      <img class="u-expanded-width u-image u-image-1" src="/media/images/20.jpg" data-image-width="770" data-image-height="420">
                      <h4 class="u-text u-text-default u-text-2">TCE</h4>
                      <p class="u-text u-text-3">Aqui encontrarás diferentes componentes tecnologicos, esta es una tienda busca lo que necesites.</p>
                    </div>
                  </div>
                  <div class="u-container-style u-hidden-sm u-hidden-xs u-layout-cell u-size-20 u-layout-cell-2">
                    <div class="u-container-layout u-container-layout-2"></div>
                  </div>
                </div>
              </div>
              <div class="u-size-20">
                <div class="u-layout-col">
                  <div class="u-container-style u-hidden-sm u-hidden-xs u-layout-cell u-size-20 u-layout-cell-3">
                    <div class="u-container-layout u-container-layout-3"></div>
                  </div>
                  <div class="u-align-center u-container-style u-layout-cell u-size-40 u-white u-layout-cell-4">
                    <div class="u-container-layout u-container-layout-4">
                      <img class="u-expanded-width u-image u-image-2" src="media/images/13.jpg" data-image-width="1960" data-image-height="1103">
                      <h4 class="u-text u-text-4">HOMEDUINO</h4>
                      <p class="u-text u-text-5">Dentro de esta parte de nuestra página encontrarás la manera de como controlar las luces de tu casa mediante arduino y una conexión web<br>Quedate a ver que ocurre!
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="u-size-20">
                <div class="u-layout-col">
                  <div class="u-align-center u-container-style u-layout-cell u-size-40 u-white u-layout-cell-5">
                    <div class="u-container-layout u-container-layout-5">
                      <img class="u-expanded-width u-image u-image-3" src="media/images/01.jpg" data-image-width="450" data-image-height="253">
                      <h4 class="u-text u-text-default u-text-6">INFOMATICA</h4>
                      <p class="u-text u-text-7">Dentro de esta parte de nuestro proyecto encontrarás lo que es noticias de último tiempo sobre tecnología, no te quedes con la duda entra!!</p>
                    </div>
                  </div>
                  <div class="u-container-style u-hidden-sm u-hidden-xs u-layout-cell u-size-20 u-layout-cell-6">
                    <div class="u-container-layout u-container-layout-6"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <p class="u-align-center u-text u-text-8">Images from <a href="https://freepik.com/photos/people" class="u-active-none u-border-1 u-border-black u-btn u-button-link u-button-style u-hover-none u-none u-text-body-color u-btn-1">Freepik</a>
        </p>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-image u-shading u-section-2" src="" data-image-width="256" data-image-height="256" id="sec-bdc5">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-text u-text-default u-title u-text-1">GREYMAC</h1>
        <p class="u-large-text u-text u-text-default u-text-variant u-text-2">Somos estudiantes de tecsup del 4to semestre en diseño y desarrollo de Sotfware</p>
      </div>
    </section>
    <section class="u-clearfix u-section-3" id="sec-8f6b">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-image u-layout-cell u-size-30 u-image-1" data-image-width="1600" data-image-height="1600">
                <div class="u-container-layout u-container-layout-1"></div>
              </div>
              <div class="u-align-center u-container-style u-layout-cell u-size-30 u-layout-cell-2">
                <div class="u-container-layout u-valign-middle u-container-layout-2">
                  <h2 class="u-text u-text-default u-text-1">&nbsp;Página de servicios&nbsp;</h2>
                  <p class="u-text u-text-default u-text-2">Nuestro proyecto trata principalmente en controlar las luces de tu hogar desde algún lugar que te encuentres ,este tiene tanto interfaz web como movil.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-340a"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">Encuentranos como:&nbsp;<br>GREYMAC@gmail.com
        </p>
      </div></footer>
    
  </body>
</html>

WEBPROJECT/index/templates/Contact.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Contact</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
<link rel="stylesheet" href="Contact.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.1.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"logo": "images/default-logo.png"
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Contact">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body"><header class="u-clearfix u-header u-header" id="sec-e304"><div class="u-clearfix u-sheet u-sheet-1">
        <a href="https://nicepage.com" class="u-image u-logo u-image-1">
          <img src="images/default-logo.png" class="u-logo-image u-logo-image-1">
        </a>
      </div></header> 
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-340a"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">Encuentranos como:&nbsp;<br>GREYMAC@gmail.com
        </p>
      </div></footer>
    <section class="u-backlink u-clearfix u-grey-80">
      <a class="u-link" href="https://nicepage.com/website-templates" target="_blank">
        <span>Website Templates</span>
      </a>
      <p class="u-text">
        <span>created with</span>
      </p>
      <a class="u-link" href="" target="_blank">
        <span>Website Builder Software</span>
      </a>. 
    </section>
  </body>
</html>

WEBPROJECT/index/templates/TCE.html
{% extends "layout.html" %}
{% block content %}

  <!-- /Block Content -->
  <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="row">
    {% for prod in product_list %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{{ prod.imagen.url }}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="#">{{ prod.nombre }}</a>
          </h4>
          <h5>S/. {{ prod.precio }}</h5>
          <p class="card-text">Categoria: {{ prod.categoria.nombre }}</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
        </div>
      </div>
    </div>
    {% endfor %}

    <!-- /Block Content -->
  </div>
  {% endblock %}

WEBPROJECT/index/templates/homeduino.html
{% extends "layout.html" %}
{% block content %}

<br></br>
<div class="container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center mt-2">
                <h1>HABITACIONES</h1>
            </div>
        </div>
        <H2>HABITACIONES</H2>
        <div class="cards" style="display: flex; width: 100%;">
            {% load static %}
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="1" name="id">
                    <button class = "hovi">DORMITORIO</button> <br>
                </form>
            </div>
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="2" name="id">
                    <button class = "hovi2">SALA</button> <br>
                </form>
            </div>
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="3" name="id">
                    <button class = "hovi3">COCINA</button> <br>
                </form>
            </div>
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="4" name="id">
                    <button class = "hovi4">BAÑO</button> <br>
                </form>
            </div>

        </div>
        <div class="row">
            <div class="col-12 text-center">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="5" name="id">
                    <button class="btn btn-dark mb-2 w-100">Apagar todo</button> <br>
                </form>
            </div>
        </div>
        <H2>COMPONENTES</H2>
        <div class="cards" style="display: flex; width: 100%;">
            {% load static %}
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="1" name="id">
                    <button class = "hovi">Room 1</button> <br>
                </form>
            </div>
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="2" name="id">
                    <button class = "hovi">Room 2</button> <br>
                </form>
            </div>
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="3" name="id">
                    <button class = "hovi">Room 3</button> <br>
                </form>
            </div>
            <div class="card"
                style=" width: 100%; height: 250px;">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="4" name="id">
                    <button class = "hovi">Room 4</button> <br>
                </form>
            </div>

        </div>
        <div class="row">
            <div class="col-12 text-center">
                <form method="POST">{% csrf_token %}
                    <input type="hidden" value="5" name="id">
                    <button class="btn btn-dark mb-2 w-100">Apagar todo</button> <br>
                </form>
            </div>
        </div>
    </div>
    <!-- Custom Scripts -->

    {% endblock %}

WEBPROJECT/index/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>PROYECTO</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" href="{% static 'css/extra.css' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/slate.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/master.css' %}" rel="stylesheet">
  <script src="{% static 'js/master.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery.poptrox.min.js' %}"></script>
  <script src="{% static 'js/browser.min.js' %}"></script>
  <script src="{% static 'js/breakpoints.min.js' %}"></script>
  <script src="{% static 'js/util.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#"><h1 style="color: aliceblue;">GRAMM</h1></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
    
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/TCE">TCE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/homeduino">HomeDuino</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/infomatica">Infomatica</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content -->
  <br></br>
  <br></br>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <h1 class="my-4">{{request.session.nombrePagina}}</h1>
        <div class="list-group">
          {% for key,value in request.session.category_list.items %}
          <a href="{% url 'index:categoria' value.id %}" class="list-group-item">{{ value.nombre }}</a>
          {% endfor %}
        </div>
        
      </div>
      <!-- /.col-lg-3 -->
      <div class="col-lg-9">
        {% block content %}
        {% endblock%}
        <!-- /.row -->
      </div>
      <!-- /.col-lg-9 -->
  </div>
  <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

WEBPROJECT/index/templates/producto.html
{% extends "layout.html" %}
{% block content %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ producto.imagen.url }}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1"></div>
                <h1 class="display-5 fw-bolder">{{ producto.nombre }}</h1>
                <div class="fs-5 mb-5">
                    <span>S/. {{ producto.precio }}</span>
                </div>
                <p class="lead"></p>
                <div class="d-flex">
                    <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                    <a class="btn btn-primary" href="{% url 'index:agregarCarrito' producto.id %}" role="button">Agregar Carrito</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}